Student_Feedback/Areas/Admin/Controllers/LocationAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gios_mvcSolution.Models;

namespace Gios_mvcSolution.Areas.Admin.Controllers
{
    public class LocationAdminController : Controller
    {
        SVC svcDao = new SVC();

        // GET: Admin/LocationAdmin
        public ActionResult Index()
        {
            BusinessUnit BU = new BusinessUnit();
            BU.BUs = svcDao.ListBusinessUnits().ToList();
            return View(BU.BUs);
        }
        public ActionResult ListSegment()
        {
            BUSegment Seg = new BUSegment();
            Seg.Segments = svcDao.ListSegments().ToList();
            return PartialView(Seg.Segments);
        }

        // GET: LocationAdmin/Create
        public ActionResult CreateBU()
        {
            return PartialView();
        }

        // POST: LocationAdmin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBU([Bind(Include = "strBUID, strBUDescr, strGroupID, strCreatorID")] BusinessUnit NewBU)
        {

            try
            {
                string message = svcDao.CreateEditBUsinessUnit("I", NewBU);

                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAdmin/Edit/5
        public ActionResult EditBU(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var businessUnitToUpdate = svcDao.FindBusinessUnit(id);
            BusinessUnit BU = businessUnitToUpdate;
            if (BU == null)
            {
                return HttpNotFound();
            }
            return PartialView(BU);
        }

        // POST: LocationAdmin/Edit/5
        [HttpPost]
        public ActionResult EditBU(string id, [Bind(Include = "strBUID, strBUDescr, strGroupID,dtmCreated, strCreatorID, dtmModified, strModifierID")] BusinessUnit modifiedBU)
        {
            try
            {
                string message = svcDao.CreateEditBUsinessUnit("U", modifiedBU);

                ViewBag.Err = message;
                return RedirectToAction("Index");


            }
            catch
            {
                return View();
            }
        }

        // GET: LocationAdmin/Delete/5
        public ActionResult DeleteBU(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var businessUnitToUpdate = svcDao.FindBusinessUnit(id);
            BusinessUnit BU = businessUnitToUpdate;
            if (BU == null)
            {
                return HttpNotFound();
            }
            return PartialView(BU);
        }

        // POST: LocationAdmin/Delete/5
        //[HttpPost]
        //public ActionResult DeleteBU(string id, [Bind(Include ="strBUID")] BusinessUnit deleteBU)
        //{
        //    //try
        //    //{
        //    //    string message = svcDao.RemoveBusinessUnit("D", deleteBU);

        //    //    ViewBag.Err = message;
        //    //    return RedirectToAction("Index");


        //    //}
        //    //catch
        //    //{
        //    //    return View();
        //    //}
        //}
    }
}

Student_Feedback/Areas/Admin/Views/LocationAdmin/CreateBU.cshtml
@model Gios_mvcSolution.Models.BusinessUnit

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BusinessUnit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.strBUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strBUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strBUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strBUDescr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strBUDescr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strBUDescr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strGroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strGroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.dtmCreated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dtmCreated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dtmCreated, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.strCreatorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strCreatorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strCreatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.dtmModified, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dtmModified, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dtmModified, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.strModifierID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.strModifierID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.strModifierID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-dark" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Student_Feedback/Areas/Admin/Views/LocationAdmin/EditBU.cshtml
@model Gios_mvcSolution.Models.BusinessUnit


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.strBUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strBUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strBUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strBUDescr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strBUDescr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strBUDescr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strGroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strGroupID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strGroupID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dtmCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dtmCreated, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.dtmCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strCreatorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strCreatorID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.strCreatorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strModifierID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strModifierID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strModifierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Student_Feedback/Areas/Admin/Views/LocationAdmin/Index.cshtml
@{
    ViewBag.Title = "Create / Modify BU";
}

<script>

    function loadPartialBUView(viewToLoad, id)
    {
        console.log("Button Click");
        console.log(viewToLoad);
        $('#viewLoadBUDiv').empty();
        if (viewToLoad === "Create") {
            $.get('@Url.Action("CreateBU", "LocationAdmin")', function (data) {
               // console.log(data);
                $('#viewLoadBUDiv').html(data);
            });
        }
         if (viewToLoad === "Edit") {
             console.log(id);
             $.get('@Url.Action("EditBU", "LocationAdmin")/' + id, function (data) {
             //   console.log(data);
                $('#viewLoadBUDiv').html(data);
            });

        }
        if (viewToLoad === "Delete") {
             console.log(id);
             $.get('@Url.Action("DeleteBU", "LocationAdmin")/' + id, function (data) {
             //   console.log(data);
                $('#viewLoadBUDiv').html(data);
            });

        }
    }

    function loadPartialSegmentView(viewToLoad, id)
    {
        console.log("Button Click");
        console.log(viewToLoad);
        $('#viewLoadSegDiv').empty();
        if (viewToLoad === "Create") {
            $.get('@Url.Action("CreateSeg", "LocationAdmin")', function (data) {
               // console.log(data);
                $('#viewLoadSegDiv').html(data);
            });
        }
         if (viewToLoad === "Edit") {
             console.log(id);
             $.get('@Url.Action("EditSeg", "LocationAdmin")/' + id, function (data) {
             //   console.log(data);
                 $('#viewLoadSegDiv').html(data);
            });

        }
        if (viewToLoad === "Delete") {
             console.log(id);
             $.get('@Url.Action("DeleteSeg", "LocationAdmin")/' + id, function (data) {
             //   console.log(data);
                $('#viewLoadSegDiv').html(data);
            });

        }
    }

</script>

<!--  BUSINESS UNIT  -->
<div>

    @Html.Partial("ListBusinessUnits")
    <hr />

    <div id="viewLoadBUDiv">

    </div>

</div>

<!-- Segment-->
<div>

    @Html.Action("ListSegment", "LocationAdmin")

    <hr />

    <div id="viewSegDiv">

    </div>

</div>

Student_Feedback/Areas/Admin/Views/LocationAdmin/ListBusinessUnits.cshtml
@model IEnumerable<Gios_mvcSolution.Models.BusinessUnit>

<h2>Create / Modify BU</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.strBUID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strBUDescr)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.dtmCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strCreatorID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtmModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strModifierID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.strBUID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strBUDescr)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.dtmCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strCreatorID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dtmModified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strModifierID)
            </td>
            <td>
                @*//@Html.ActionLink("Edit", "EditBU", new { id=item.strBUID  }) |*@
                <button class="btn btn-default" onclick="loadPartialBUView('Edit', this.id)" id="@item.strBUID">Edit</button>|
                <button class="btn btn-default" onclick="loadPartialBUView('Delete', this.id)" id="@item.strBUID">Remove</button>
            </td>
        </tr>
    }

</table>
<hr />
<div>
    @* @Html.ActionLink("Create New", "Create", null, new { @id = "Create" })*@
    <button class="btn btn-dark" onclick="loadPartialBUView('Create', this.id)" id="Create"> Create New BU</button>
</div>

Student_Feedback/Areas/Admin/Views/LocationAdmin/ListSegment.cshtml
@model IEnumerable<Gios_mvcSolution.Models.BUSegment>

<h2>Create / Modify BU Segments</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.strSegmentID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strSegmentDescr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strBUID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtmCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strCreatorID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dtmModified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.strModifierID)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.strSegmentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strSegmentDescr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strBUID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dtmCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strCreatorID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dtmModified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.strModifierID)
            </td>
            <td>
                @*//@Html.ActionLink("Edit", "EditBU", new { id=item.strBUID  }) |*@
                <button class="btn btn-default" onclick="loadPartialSegView('Edit', this.id)" id="@item.strSegmentID">Edit</button>|
                <button class="btn btn-default" onclick="loadPartialSegView('Delete', this.id)" id="@item.strSegmentID">Remove</button>
            </td>
        </tr>
    }

</table>
<hr />
<div>
    @* @Html.ActionLink("Create New", "Create", null, new { @id = "Create" })*@
    <button class="btn btn-dark" onclick="loadPartialSegView('Create', this.id)" id="Create"> Create New Segment</button>
</div>