Student_Feedback/Areas/GIOS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gios_mvcSolution.Areas.GIOS.Controllers
{
    public class HomeController : Controller
    {
        // GET: GIOS/Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PageNotFound()
        {
            ViewBag.Error = TempData["Error"].ToString();
            return View();
        }
    }
}

Student_Feedback/Areas/Mios/Controllers/MiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gios_mvcSolution.Areas.Mios;
using Gios_mvcSolution.Models;

namespace Gios_mvcSolution.Areas.Mios.Controllers
{
    public class MiosController : Controller
    {
        SVC svcDao = new SVC();
        // GET: Mios/Mios
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DataEntry()
        {

            BusinessUnit BU = new BusinessUnit();

            BU.BuList = new SelectList(svcDao.GetBusinessUnits(), "strBUID", "strBUID");


            return View(BU);
        }


        //GET: Location Hier DATA ASYNC
        // level represents Level to retrieve
        //[HttpPost]
        //public ActionResult GetLocationHierData(string level, string id)
        //{
        //    if (level == "Seg")
        //    {
        //        BUSegment Segment = new BUSegment();
        //        Segment.SegmentSelectList = new SelectList(svcDao.GetSegments(id), "strSegmentID", "strSegmentDescr");
        //        return Json(Segment.SegmentSelectList, JsonRequestBehavior.AllowGet);
        //    }
        //    else if (level == "Loc")
        //    {
        //        Location Loc = new Location();
        //        Loc.LocList = new SelectList(svcDao.GetLocations(id), "strLocationID", "strLocationDescr");
        //        return Json(Loc.LocList, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        return View("DUMMY");
        //    }


        //}

        // GET: Mios/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Mios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mios/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mios/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Mios/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Mios/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Mios/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Student_Feedback/Areas/GIOS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Student_Feedback/Areas/GIOS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to GIOS</h1>
    <p class="lead">
        Global Intelligence Operating System Smart. Create a digital platform to enable operational continuous improvements and advance Smart manufacturing through People and Technology
    </p>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Getting started</h2>
        <p>
            Are you a Plant Manger Looking to get started on your Smart Journey, this is place for you
        </p>
        <p><button class="btn btn-default">Learn more &raquo;</button></p>
    </div>
    <div class="col-md-3">
        <h2>MIOS <br /></h2>
        <h5>(Manufacutring Intelligence Operating Systems)</h5>
        <p>Enter KPI Data and View the overall health of a Location, Line or Process across Arconic</p>
        <p><button class="btn btn-default" onclick="window.location='@Url.Action("DataEntry", "Mios")'">Learn more &raquo;</button></p>
    </div>
    <div class="col-md-3">
        <h2>Use Case</h2>
        <p>Have an idea on how to save your BU Time, or Money submit your idea here and let the your BU's COE know</p>
        <p><a class="btn btn-default" onclick="window.location='@Url.Action("Index", "UseCase")'">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Training</h2>
        <p>Learn More about a given role, or competancy. See what knowledge gaps you have and get recommended training to fill them</p>
        <p><a class="btn btn-default" onclick="window.location='@Url.Action("Index", "Training")'">Learn more &raquo;</a></p>
    </div>
</div>

Student_Feedback/Areas/GIOS/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "PageNotFound";
}

<h2>PageNotFound</h2>

<h3> @ViewBag.Error</h3>