Student_Feedback/Areas/UseCase/Models/CompassCat.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gios_mvcSolution.Areas.UseCase.Models
{
    public class CompassCat
    {
        [Key]
        [Display(Name="Category Name")]
        [Required]
        public string strCategoryID { get; set; }

        [Display(Name ="Category Description")]
        [Required]
        public string strCategoryDescr { get; set; }
        
        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }

        [NotMapped]
        public SelectList CategoryDDL { get; set; }

        public IList CategoryList { get; set; }
    }
}

Student_Feedback/Areas/UseCase/Models/FileTypes.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Gios_mvcSolution.Areas.UseCase.Models
{
    public class FileTypes
    {
        [Key]
        [Display(Name ="File Extension")]
        public string strFileType { get; set; }

        [Display(Name ="File Description")]
        public string strFileDescription { get; set; }

        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }

        public IList FileTypeList { get; set; }

    }
}

Student_Feedback/Areas/UseCase/Models/ImpactKPI.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Gios_mvcSolution.Areas.UseCase.Models
{
    public class ImpactKPI
    {
        [Display(Name = "Support Type ID")]
        [Key]
        public int intImpactKPIID { get; set; }

        [Display(Name = "KPI Name")]
        public string strKPI { get; set; }

        [Display(Name = "KPI Description")]
        public string strKPIDescr { get; set; }

        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }

        public bool isSelected { get; set; }

        [NotMapped]
        public IList impactKPIList { get; set; }
    }

    public class UseCaseImpactKPI
    {
        public string strKPI { get; set; }
        public int intUseCaseID { get; set; }

        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }
    }

}

Student_Feedback/Areas/UseCase/Models/RequiredSupportTypes.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Gios_mvcSolution.Areas.UseCase.Models
{
    public class RequiredSupportTypes
    {
        [Display(Name = "Support Type ID")]
        [Key]
        public int intSupportTypeID { get; set; }

        [Display(Name = "Support Type")]
        public string strSupportType { get; set; }

        [Display(Name ="Support Type Description")]
        public string strSupportTypeDescr { get; set; }

        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }

        public bool isSelected { get; set; }

        [NotMapped]
        public IList RequiredSupportList { get; set; }
    }

    public class UseCaseExtraSupport
    {
        [Key]
        public int lngRecordID { get; set; }

        public int intUseCaseID { get; set; }

        public string strSupportType { get; set; }

        [Display(Name = "Date Created")]
        public Nullable<System.DateTime> dtmCreated { get; set; }
        [Display(Name = "Created By")]
        public string strCreatorID { get; set; }
        [Display(Name = "Last Modified")]
        public Nullable<System.DateTime> dtmModified { get; set; }
        [Display(Name = "Modified By")]
        public string strModifierID { get; set; }


    }
}

Student_Feedback/Areas/UseCase/Controllers/AdminController.cs
using Gios_mvcSolution.Areas.UseCase.Models;
using Gios_mvcSolution.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Gios_mvcSolution.Areas.UseCase.Controllers
{
    public class AdminController : Controller
    {
        UseCase_DAL useCase_DAL = new UseCase_DAL(); 
        
        // GET: UseCase/Admin
        public ActionResult Index()
        {
            return View();
        }

        #region Required Support Types List, Create, Modify
        public ActionResult ListRequiredSupport()
        {
            RequiredSupportTypes requiredSupportTypes = new RequiredSupportTypes();
            requiredSupportTypes.RequiredSupportList = useCase_DAL.ListrequiredSupportTypes().ToList();
            return PartialView(requiredSupportTypes.RequiredSupportList);
        }


        // GET: UseCase/Admin/CreateRequiredSupport
        public ActionResult CreateRequiredSupport()
        {
            return PartialView();
        }

        // POST: UseCase/Admin/CreateRequiredSupport
        [HttpPost]
        public ActionResult CreateRequiredSupport([Bind(Include = "strSupportType, strSupportTypeDescr")] RequiredSupportTypes newSupportType)
        {
            try
            {

                newSupportType.strCreatorID = GetUserID();
                string message = useCase_DAL.CreateEditRequiredSupportType("I", newSupportType);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
               // ViewBag.Err(ex.Message);
                return View();
            }
        }



        // GET: UseCase/Admin/Edit/5
        public ActionResult UpdateRequiredSupport(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var supportTypeToEdit = useCase_DAL.FindRequiredSupportType(id);
            RequiredSupportTypes reqSupType = supportTypeToEdit;
            return PartialView(reqSupType);
        }

        // POST: UseCase/Admin/Edit/5
        [HttpPost]
        public ActionResult UpdateRequiredSupport(int id, [Bind(Include = "intSupportTypeID, strSupportType, strSupportTypeDescr, strCreatorID")] RequiredSupportTypes modSupportType)
        {
            try
            {
                // TODO: Add update logic here
                modSupportType.strModifierID = GetUserID();
                string message = useCase_DAL.CreateEditRequiredSupportType("U", modSupportType);

                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region File Types List,Create,Modify
        public ActionResult ListFileTypes()
        {
            FileTypes fileTypes = new FileTypes();
            fileTypes.FileTypeList = useCase_DAL.ListFileTypes().ToList();
            return PartialView(fileTypes.FileTypeList);
        }

        public ActionResult CreateFileType()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateFileType ([Bind(Include = "strFileType, strFileDescription")] FileTypes newFileType)
        {
            try
            {
                newFileType.strCreatorID = GetUserID();
                string message = useCase_DAL.CreateEditFileType("I", newFileType);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                // ViewBag.Err(ex.Message);
                return View();
            }
        }

        public ActionResult UpdateFileType(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fileTypeToEdit = useCase_DAL.FindFileType(id);
            FileTypes fileTypes = fileTypeToEdit;
            return PartialView(fileTypes);
        }

        [HttpPost]
        public ActionResult UpdateFileType(string id, [Bind(Include ="strFileType, strFileDescription, strCreatorID")] FileTypes modFileType)
        {
            try
            {
                // TODO: Add update logic here
                modFileType.strModifierID = GetUserID();
                string message = useCase_DAL.CreateEditFileType("U", modFileType);

                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        #endregion

        #region Status List, Create, Modify

        public ActionResult ListStatus()
        {
            Status status = new Status();
            status.StatusList = useCase_DAL.ListStatuses().ToList();
            return PartialView(status.StatusList);
        }

        public ActionResult CreateStatus()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateStatus([Bind(Include ="strStatus, strDescription, yesActive")] Status newStatus)
        {
            try
            {
                newStatus.strCreatorID = GetUserID();
                string message = useCase_DAL.CreateEditStatus("I", newStatus);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                // ViewBag.Err(ex.Message);
                return View();
            }
        }

        public ActionResult UpdateStatus(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var StatusToEdit = useCase_DAL.FindStatus(id);
            Status status = StatusToEdit;
            return PartialView(status);
        }

        [HttpPost]
        public ActionResult UpdateStatus(string id, [Bind(Include ="strStatus, strDescription, yesActive, strCreatorID")] Status modStatus)
        {
            try
            {
                // TODO: Add update logic here
                modStatus.strModifierID = GetUserID();
                string message = useCase_DAL.CreateEditStatus("U", modStatus);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        #endregion

        #region Impact KPI List, Create, Modify
        public ActionResult ListImpactKPI()
        {
            ImpactKPI impactKPI = new ImpactKPI()
            {
                impactKPIList = useCase_DAL.ListImpactKPIs().ToList()
            };
            return PartialView(impactKPI.impactKPIList);
        }

        public ActionResult CreateImpactKPI()
        {
            return PartialView();

        }

        [HttpPost]
        public ActionResult CreateImpactKPI([Bind(Include = "strKPI, strKPIDescr")] ImpactKPI newImpactKPI)
        {
            try
            {
                newImpactKPI.strCreatorID = GetUserID();
                string message = useCase_DAL.CreateEditImpactKPI("I", newImpactKPI);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                // ViewBag.Err(ex.Message);
                return View();
            }
        }

        public ActionResult UpdateImpactKPI(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var KPIToEdit = useCase_DAL.FindImpactKPI(id);
            ImpactKPI impact = KPIToEdit;
            return PartialView(impact);
        }

        [HttpPost]
        public ActionResult UpdateImpactKPI(string id, [Bind(Include = "strKPI, strKPIDescr, strCreatorID")] ImpactKPI impactKPI)
        {
            try
            {
                // TODO: Add update logic here
                impactKPI.strModifierID = GetUserID();
                string message = useCase_DAL.CreateEditImpactKPI("U", impactKPI);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        #endregion


        #region Compass Cat List, Create, Modify
        public ActionResult ListCompassCat()
        {
            CompassCat compassCat = new CompassCat
            {
                CategoryList = useCase_DAL.ListCompassCats().ToList()
            };
            return PartialView(compassCat.CategoryList);
        }

        public ActionResult CreateCompassCat()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateCompassCat([Bind(Include = "strCategoryID, strCategoryDescr")] CompassCat newCompassCat)
        {
            try
            {
                newCompassCat.strCreatorID = GetUserID();
                string message = useCase_DAL.CreateEditCompassCat("I", newCompassCat);
                ViewBag.Err = message;
                return RedirectToAction("Index");
            }
            catch
            {
                // ViewBag.Err(ex.Message);
                return View();
            }
        }

        public ActionResult UpdateCompassCat(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var CompassCatToEdit = useCase_DAL.FindCompassCat(id);
            CompassCat compassCat = CompassCatToEdit;
            return PartialView(compassCat);
        }

        [HttpPost]
        public ActionResult UpdateCompassCat(string id, [Bind(Include = "strCategoryID, strCategoryDescr, strCreatorID")] CompassCat modCompassCat)

Student_Feedback/Areas/UseCase/Controllers/UseCaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gios_mvcSolution.Models;

namespace Gios_mvcSolution.Areas.UseCase.Controllers
{
    public class UseCaseController : Controller
    {
        // GET: UseCase/UseCase
        public ActionResult Index()
        {
            return View();
        }

        // GET: UseCase/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UseCase/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UseCase/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UseCase/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UseCase/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UseCase/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UseCase/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Student_Feedback/Areas/UseCase/Views/UseCase/Index.cshtml
@{
    ViewBag.Title = "Use Case Home";
}


<div class="jumbotron">
    <h1>Use Cases</h1>
    <p class="lead">Welcome to the Use Case Module, please click the button for the action that best fits your reason for visiting. Are you to create, update, or search for new ideas?</p>

</div>

<div class="row">
    <div class="col-sm-3">
        <input type="button" value="New Use Case" onclick="window.location='@Url.Action("Create", "UseCase")'" />

        <button> Update Use Case</button>
        <button> Search Exisiting Use Case</button>
    </div>
</div>

Student_Feedback/Areas/UseCase/Views/UseCase/Phase2.cshtml
@model Gios_mvcSolution.Areas.UseCase.ViewModels.Phase2_Update

@{
    ViewBag.Title = "Use Case";
}


<row>
    <h2>Use Case</h2>
    <button onclick="unlockForm()" class="btn-dark btn"> Edit Exisiting Data</button>
</row>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Student_Feedback/Areas/UseCase/Views/UseCase/UseCase.cshtml
@{
    ViewBag.Title = "Create New Use Case";
    ViewBag.Description = "Create New Use Case - allows for creation, setting of new use case values and file attachment";
}

<script>
    var oldVals = [];
    var newVals = [];
    // var fileTypes = [];
    var impactKPIVals = [];
    var oldKPIVals = [];

    function activateFields() {
        $('#strAssests').prop('disabled', false);
        $('#strTeam').prop('disabled', false);
    }

    function updateImpactKPIList(checkedOption) {
        oldKPIVals = impactKPIVals;
        impactKPIVals = [];
        $('.reqKPI:checked').each(function () {
            impactKPIVals.push(this.id);
        });
        $('#SelectedImpactKPIs').prop('value', impactKPIVals);
    }

    function updateSupportList(checkedOption) {
        oldVals = newVals;
        newVals = [];
       // console.log("Old Selected Options: " + oldVals);
       // console.log("Checked Option Param: " + checkedOption);
        if (checkedOption === "N/A") {
            var exisits = oldVals.indexOf(checkedOption);
            if (exisits === -1) {
                $('.reqSupp').prop('disabled', true);
                $('.reqSupp').prop('checked', false);
                $('#strReqSupportOther').prop('value', "");
                $('#intCAPEXEstimate').prop('value', "");
                $('#OtherOption').css("display", "none");
                $('#CapexEstimate').css("display", "none");
                $('#N\\/A').prop('disabled', false);
                $('#N\\/A').prop('checked', true);
                $('#status').prop('value', "Draft");
            }
            else {
                $('.reqSupp').prop('disabled', false);
                $('#status').prop('value', "Draft");
            }
        }
        else if (checkedOption === "Other") {
            var exisits = oldVals.indexOf(checkedOption);
            if (exisits === -1) {
                $('#OtherOption').css("display","block");
            }
            else {
                $('#OtherOption').css("display","none");
                $('#strReqSupportOther').prop('value', "");
            }
            $('#status').prop('value', "Under Review");
        }
        else if (checkedOption === "CAPEX") {
            var exisits = oldVals.indexOf(checkedOption);
            if (exisits === -1) {
                $('#CapexEstimate').css("display", "block");
            }
            else {
                $('#CapexEstimate').css("display", "none");
                $('#intCAPEXEstimate').prop('value', "");
            }
            $('#status').prop('value', "Under Review");
        }
        $('.reqSupp:checked').each(function () {
            newVals.push(this.id);
        });
        //$('#status').prop('value', "Under Review");
        $('#SelectedSupport').prop("value", newVals);
       // console.log("List of Selected Options: " + newVals);
    }

    function getSupportedFileTypes() {
        var obj = { id: "FileTypes" }
        fileTypes = [];
        AjaxCall('/UseCase/Admin/FileTypeList', JSON.stringify(obj), 'POST').done(function (response) {
            if (response.length > 0) {
                for (var i = 0; i < response.length; i++) {
                    fileTypes.push('.' + response[i].strFileType);
                }
                $('#AttachmentLabel').append('<small class="form-text text-muted"> Permitted Files: ' + fileTypes.join() + '</small>');
            }
        }).fail(function (error) {
            alert(error.StatusText);
        });
    }

    function fileValidation() {
        var fileTypes = []
        fileTypes = $('#permittedFiles').html().split(', ');
        console.log(fileTypes);
        var fileToUpload = $('#file-upload').val();
        var fileTypeRegEx = new RegExp(fileTypes.join("|", 'gi'));
        console.log(fileTypeRegEx);
        if (!fileTypeRegEx.exec(fileToUpload)) {
            // alert("The File You tried to upload is invalid, please use an accepted file type");
            $('#errors').html('<div class= "alert alert-danger alert-dismissible fade show" role = "alert" id = "errorMessage" > ' +
                '<small id="errorMessageText">The File You tried to upload is invalid, please use an accepted file type</small>' +
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                '   <span aria-hidden="true">&times;</span>  </button> </div >');
            $('#Attachment').val("");
            $('#strFileType').val("");
        }
        else {
            $('#errors').html('<div class= "alert alert-success alert-dismissible fade show" role = "alert" id = "errorMessage" > ' +
                '<small id="errorMessageText">Your file has been succesfully attached to the Use Case</small>' +
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                '   <span aria-hidden="true">&times;</span>  </button> </div >');
            $('#strFileType').val(getExtension(fileToUpload));
        }
    }

    function getExtension(path) {
        var basename = path.split(/[\\/]/).pop(),  // extract file name from full path ...
            // (supports `\\` and `/` separators)
            pos = basename.lastIndexOf(".");       // get last position of `.`
        if (basename === "" || pos < 1)            // if file name is empty or ...
            return "";                             //  `.` not found (-1) or comes first (0)

        return basename.slice(pos + 1);            // extract extension ignoring `.`
    }

    function sensitiveUseCase() {
        var isChecked = $('#ysnITAR').prop('checked');
        console.log(isChecked);
        if (isChecked) {
            //$('#errorMessage').html('Due to the sensitivity of the Use Case, you are not permitted to Attach a File at this time');
            //$('#errorMessage').prop("visibilty", true);
            $('#errors').html('<div class= "alert alert-warning alert-dismissible fade show" role = "alert" id = "errorMessage" > ' +
                '<small id="errorMessageText">Due to the sensitivity of the Use Case, you are not permitted to Attach a File at this time</small>' +
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                '   <span aria-hidden="true">&times;</span>  </button> </div >');
            $('#Attachment').prop("disabled", true);
            $('#Attachment').val("");
            $('#strFileType').val("");
        }
        else
            $('#Attachment').prop("disabled", false);
    }

    // Shows KPI Definition div on KPI link click - Radu 02.12.2019 issue 160
    function showKPIDefinition(id) {
        $("[id=div_" + id + "]").toggle(); // toggles visibility on div
        //$("[id=div_" + id + "]").removeClass('divHide'); 
        //$("[id=div_" + id + "]").addClass('divShow'); 
    }
</script>

<!-- Heading -->
<div>
    @*<i class="fas fa-vector-square fontAwesomePageTitle"></i>*@
    <span class="fontSegoeUI_Bold">Create</span>
    <span class="boxTeal25Percent fontSize33px fontSegoeUI_Bold">New</span>
    <span class="fontSize33px fontSegoeUI_Regular">Use Case</span>
</div>
<div class="spacer-5px"></div>

<!-- bread crumbs -->
<div class="hideOnMobile">
    <div class="greyLine" style="margin-bottom: 3px;"></div>
    <span>
        &nbsp;&nbsp;<i class="fa fa-tags breadcrumbsIcons"></i><span class="greyBoxDarkerMorePadding breadcrumbsText" style="margin-left:6px;">Resources</span>
    </span>
    <span>
        &nbsp;&nbsp;
        <i class="fa fa-paper-plane breadcrumbsIcons"></i>&nbsp;&nbsp;<a class="breadcrumbsLink" href="@Url.Action("Index", "Home")">Home</a>
        <i class="fa fa-angle-right active breadcrumbsIcons"></i>&nbsp;<span class="breadcrumbsText">Use Cases</span>
        <i class="fa fa-angle-right active breadcrumbsIcons"></i>&nbsp;<span class="breadcrumbsText">Create New Use Case</span>
    </span>
    <div class="greyLine" style="margin-top: 6px;"></div>
    <div class="spacer-30px"></div>
</div>

<div class="row">
    <div class="col-md-10">
        <!-- link below goes to 'UseCaseController.cs' which feeds 'Phase1.cshtml' partial -->
        <div>@Html.Action("Phase1", "UseCase")</div>
    </div>
    <div class="col-md-2 hideOnMobile">
        <ul class="rightSideLinksUL verticalLine">
            <li class="rightSideLinksLI">
                <a href="@Url.Action("Index", "UseCase")" class="linkRightSide">Home</a>
                @*@Html.ActionLink("Back to List", "Index")*@
            </li>
            <li class="">
                <a href="#" class="linkRightSide">Update Use Case</a>
            </li>
            <li class="toc-entry toc-h2">
                <a href="#" class="linkRightSide">Search</a>
            </li>
            <li class="toc-entry toc-h2">
                <a href="@Url.Action("Index","Admin")" class="linkRightSide">Admin</a>
            </li>
        </ul>
    </div>
</div>